---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
name: '{{ include "ndk-pairing.fullname" . }}-cluster-role-binding'
subjects:
  - kind: ServiceAccount
    name: '{{ include "ndk-pairing.fullname" . }}-sa'
    apiGroup: ""
    namespace: '{{ .Release.Namespace }}'
roleRef:
  kind: ClusterRole
  name: '{{ include "ndk-pairing.fullname" . }}-cluster-role'
  apiGroup: rbac.authorization.k8s.io