---
apiVersion: v1
kind: Secret
metadata:
  name: '{{ include "ndk-pairing.fullname" . }}-replication-sa-secret'
  annotations:
    kubernetes.io/service-account.name: '{{ include "ndk-pairing.fullname" . }}-replication-sa'
type: kubernetes.io/service-account-token