apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: app-generator
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - cluster: in-cluster
        env: source
        app: namespaces
        namespace: namespaces
      - cluster: target
        env: target
        app: namespaces
        namespace: namespaces
      - cluster: in-cluster
        env: source
        app: privatebin
        namespace: privatebin
  template:
    metadata:
      name: '{{env}}-{{app}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/LalosBastien/fantastic-happiness.git
        targetRevision: main
        path: 'applications/{{app}}'
      destination:
        name: '{{cluster}}'
        namespace: '{{namespace}}'
      # syncPolicy:
      #   automated:
      #     prune: true